DROP TABLE votes IF EXISTS;
DROP TABLE menu_items IF EXISTS;
DROP TABLE menus IF EXISTS;
DROP TABLE restaurants IF EXISTS;
DROP TABLE user_roles IF EXISTS;
DROP TABLE users IF EXISTS;
DROP SEQUENCE global_seq IF EXISTS;

CREATE SEQUENCE global_seq AS INTEGER START WITH 100000;

CREATE TABLE users
(
    id         INTEGER GENERATED BY DEFAULT AS SEQUENCE global_seq PRIMARY KEY,
    name       VARCHAR(255)            NOT NULL,
    email      VARCHAR(255)            NOT NULL,
    password   VARCHAR(255)            NOT NULL,
    registered TIMESTAMP DEFAULT now() NOT NULL,
    enabled    BOOLEAN   DEFAULT TRUE  NOT NULL
);
CREATE UNIQUE INDEX users_unique_email_idx
    ON USERS (email);

CREATE TABLE user_roles
(
    user_id INTEGER NOT NULL,
    role    VARCHAR(255),
    CONSTRAINT user_roles_idx UNIQUE (user_id, role),
    FOREIGN KEY (user_id) REFERENCES USERS (id) ON DELETE CASCADE
);

CREATE TABLE restaurants
(
    id      INTEGER GENERATED BY DEFAULT AS SEQUENCE global_seq PRIMARY KEY,
    name    VARCHAR(255)       NOT NULL,
    address VARCHAR(255)       NOT NULL,
    date    DATE DEFAULT now() NOT NULL,
    CONSTRAINT restaurants_idx UNIQUE (name, address)
);
CREATE UNIQUE INDEX restaurants_unique_name_address_idx
    ON restaurants (name, address);

CREATE TABLE menus
(
    id            INTEGER GENERATED BY DEFAULT AS SEQUENCE global_seq PRIMARY KEY,
    restaurant_id INTEGER            NOT NULL,
    date          DATE DEFAULT now() NOT NULL,
    CONSTRAINT menus_idx UNIQUE (date, restaurant_id),
    FOREIGN KEY (restaurant_id) REFERENCES restaurants (id) ON DELETE CASCADE
);
CREATE INDEX menus_date_idx
    ON menus (date);
CREATE UNIQUE INDEX menus_unique_date_restaurant_idx
    ON menus (date, restaurant_id);

CREATE TABLE menu_items
(
    id      INTEGER GENERATED BY DEFAULT AS SEQUENCE global_seq PRIMARY KEY,
    name    VARCHAR(255)   NOT NULL,
    price   DECIMAL(10, 2) NOT NULL,
    menu_id INTEGER        NOT NULL,
    CONSTRAINT menu_items_idx UNIQUE (name, menu_id),
    FOREIGN KEY (menu_id) REFERENCES menus (id) ON DELETE CASCADE
);
CREATE UNIQUE INDEX menu_items_unique_name_menu_idx
    ON menu_items (name, menu_id);

CREATE TABLE votes
(
    id            INTEGER GENERATED BY DEFAULT AS SEQUENCE global_seq PRIMARY KEY,
    date          DATE DEFAULT now() NOT NULL,
    user_email    VARCHAR(255)       NOT NULL,
    restaurant_id INTEGER            NOT NULL,
    FOREIGN KEY (restaurant_id) REFERENCES restaurants (id) ON DELETE CASCADE
);
CREATE INDEX votes_date_idx
    ON votes (date);
CREATE UNIQUE INDEX votes_unique_date_user_idx
    ON votes (date, user_email);